# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [50]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [51]:
A = np.arange(1, 16).reshape(3,5)

In [52]:
print(A.shape) # It is 3 rows and 5 columns and have elementdata 1-15
print(A.size) #  15 elements
print(type(A)) # numpy.ndarray

(3, 5)
15
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [53]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2 

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [54]:
print(B-C) # Subtraction
print()
print(B*C) # elementwise multiplication
print()
print(B @ C) # matrixmultiplication

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [55]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
np.set_printoptions(suppress=True,precision=2) # Formatting elements to 2 decimals, looks nicer
print(np.exp(D)) # exp values on each elemnt
print('Min whole matrix', np.min(D))# min for the matrix
print('Min per column', np.min(D,axis=0)) # min per column
print('Min per row', np.min(D,axis=1)) # min per row
print('Min with np.argmin ',np.argmin(D))# Returns 0 as the first element is lowest. argmin returners the value as from a onedimensionel matrix [0,val].
print('Min per row with np.argmin ',np.argmin(D, axis=1))# Return 0 as the first element in each row is lowest. argmin with axis=1 returns an array per row.
print('Sum whole matrix', np.sum(D)) # Sum whole matrix
print('Mean per column', np.mean(D, axis=0)) # Mean 
print('Median per column',np.median(D, axis=0)) # Median


[[   2.72    7.39   20.09]
 [  54.6   148.41  403.43]
 [1096.63 2980.96 8103.08]]
Min whole matrix 1
Min per column [1 2 3]
Min per row [1 4 7]
Min with np.argmin  0
Min per row with np.argmin  [0 0 0]
Sum whole matrix 45
Mean per column [4. 5. 6.]
Median per column [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [57]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [58]:
A[1]


array([ 6,  7,  8,  9, 10])

**Answer:**

In [59]:
# Return the second row in the matrix. Ie. if  A[1,1:3] returns [7, 8] index 1 to 3 in row 1
# and A[:,2] returns [3, 8, 13], column no 2

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [60]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [61]:
for i in A:
    print(i)


[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [62]:
for (row_index, the_row) in enumerate(A): # enumerate to get the rowindex
    for col_index in range(the_row.size): # The elements in the row
        print('[',row_index,',',col_index,'] = ',A[row_index,col_index]) # print where we are
    

# Reshape the array and go just with one loop to get the values
#R = A.reshape(1,A.size)
#for col_index1 in range(R.size): 
    #print(R[0,col_index1])

[ 0 , 0 ] =  1
[ 0 , 1 ] =  2
[ 0 , 2 ] =  3
[ 0 , 3 ] =  4
[ 0 , 4 ] =  5
[ 1 , 0 ] =  6
[ 1 , 1 ] =  7
[ 1 , 2 ] =  8
[ 1 , 3 ] =  9
[ 1 , 4 ] =  10
[ 2 , 0 ] =  11
[ 2 , 1 ] =  12
[ 2 , 2 ] =  13
[ 2 , 3 ] =  14
[ 2 , 4 ] =  15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [63]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [64]:
# .reshape(a,b,c) needs to be as a*b*c is equal to the size, 30 in this case
# the product of all dimensions needs to be equal to the size.
# if leaving a value to -1, numpy figures out what that dimension needs to be
# so a.reshape((2, -1, 5)) will give the same result.


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [65]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [66]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [67]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [68]:
def add_mult_matrices(mat_1, mat_2, oper):
    # Add a docstring to clearify how to call
    """ Call as add_mult_matrices(a, b, c) where 
    a is a matix b is a matrix or scalar (int) and c is a str 'add' or 'mult' """
    
    check_type = (isinstance(mat_1, np.ndarray) == (isinstance(mat_2, np.ndarray) or isinstance(mat_2, int))) # Check that parameters are ok by type
    if isinstance(mat_2, int): # Check when parameter 2 is an int
        check_type = check_type and oper=='mult'# then an scalar operation will be done        
    if check_type:
        if oper=='add' or oper=='mult':
            if oper=='add': # If addition, check both size are same
                if mat_1.shape==mat_2.shape:
                    return mat_1+mat_2
                else:
                    print('Sizes on matrix dont match on add')
                    return(-1)
                
            if oper=='mult':
                if isinstance(mat_2, int): # second parameter, mat_2 is an int, do a scalar multiplication
                    return mat_1*mat_2                    
                else:
                    if mat_1.shape[1]==mat_2.shape[0]: # if 2 matrices, check cols in A is same as rows in B
                        return mat_1 @ mat_2
                    else:    
                        print('Sizes on matrix dont match on mult')
                        return(-1)
        else:
            print('Use add or mult')
            return(-1) # wrong operand
    else:
        print('Wrong datatypes in argument')
        return(-1) # wrong datatype


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [69]:
x =  np.array([[4, 3]]) 
print(x)
print('10.0.1 ')
print('a, dimension=',x.shape)# 1*2
print('b, 5x= ', add_mult_matrices(x,5, 'mult'))
print('c, 3x= ', add_mult_matrices(x,3, 'mult') )
print('d, 5+3x= ', add_mult_matrices(x,5, 'mult')+add_mult_matrices(x,3, 'mult') )
print('e, 8x= ', add_mult_matrices(x,8, 'mult'))
print('f, 4x-x= ', add_mult_matrices(x,4, 'mult')-add_mult_matrices(x,1, 'mult'))
r = np.transpose(x) 
print('g: Transposed= ')
print(r)
print('New shape: ',r.shape)
print('h:')
print(add_mult_matrices(x,np.transpose(x),'add'))
print('i: norm= ',np.linalg.norm(x)) 
print()

v=np.array([[3],
            [7],
            [0],
            [11]])
print('10.1.2 ')
print('a: dim',v.shape)
print('b: 2v = ')
print(add_mult_matrices(v,2,'mult'))
print('c: 5v + 2v=')
print(add_mult_matrices(v,5,'mult')+add_mult_matrices(v,2,'mult'))
print('d: 4v - 2v=')
print(add_mult_matrices(v,4,'mult')-add_mult_matrices(v,2,'mult'))
s = np.transpose(v) 
print('e: transponat= ')
print(s)
print('e: new shape=', s.shape)
print('f: ||v||)= ',np.linalg.norm(v) )

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

print('10.1.3 a: ||v1|| ',np.linalg.norm(v1))
print('b: ||v1-v2|| ',np.linalg.norm(v1-v2))

[[4 3]]
10.0.1 
a, dimension= (1, 2)
b, 5x=  [[20 15]]
c, 3x=  [[12  9]]
d, 5+3x=  [[32 24]]
e, 8x=  [[32 24]]
f, 4x-x=  [[12  9]]
g: Transposed= 
[[4]
 [3]]
New shape:  (2, 1)
h:
Sizes on matrix dont match on add
-1
i: norm=  5.0

10.1.2 
a: dim (4, 1)
b: 2v = 
[[ 6]
 [14]
 [ 0]
 [22]]
c: 5v + 2v=
[[21]
 [49]
 [ 0]
 [77]]
d: 4v - 2v=
[[ 6]
 [14]
 [ 0]
 [22]]
e: transponat= 
[[ 3  7  0 11]]
e: new shape= (1, 4)
f: ||v||)=  13.379088160259652
10.1.3 a: ||v1||  7.14142842854285
b: ||v1-v2||  4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [70]:
A = np.array([[2, 1, -1], 
              [1, -1, 1]])

B = np.array([[4, -2, 1], 
              [2, -4, -2]])

C = np.array([[1, 2], 
              [2, 1]])
             
D = np.array([[3, 4], 
              [4, 3]])
E = np.array([[1],
              [2]])
I = np.array([[1, 0],
              [0, 1]])
print('10.2.1 a ')
print('a:')
print(add_mult_matrices(A, 2, 'mult'))
print('b:')
print(B-add_mult_matrices(A, 2, 'mult'))
print('c: wrong dimensions')
print(add_mult_matrices(3 * C, -2 *E, 'add'))

print('d:')
print(add_mult_matrices(D, 2, 'mult')-add_mult_matrices(C, 3, 'mult'))
print('e:')
print(np.transpose(D) + add_mult_matrices(D, 2, 'mult'))
print('f:')
print( add_mult_matrices(np.transpose(C),2,'mult') - add_mult_matrices(np.transpose(D), 2, 'mult'))
print('g:')
print( add_mult_matrices(np.transpose(A),-B,'add'))

print('h:')
print(add_mult_matrices(A, C, 'mult')) 

print('i:')
print(add_mult_matrices(C, D, 'mult'))
print('j:')
print(add_mult_matrices(C, B, 'mult'))

print('k:')
print(add_mult_matrices(C, I, 'mult'))
print('l:')
print( add_mult_matrices(A,np.transpose(B),'mult'))

print()
print('10.2.2:')
A = np.array([[2, 3, 4], 
              [5, 4, 1]])

print( add_mult_matrices(A, np.transpose(A),'mult'))

print()
print('10.2.3:')

A = np.array([[1, 2],
              [2, 4]])

B = np.array([[2, 1],
              [1, 3]])

C = np.array([[4, 3],
              [0, 2]])

print('AB =')
print( add_mult_matrices(A, B,'mult'))
print('AC =')
print( add_mult_matrices(A, C,'mult'))
print('B != C')
print(B)
print(C)


10.2.1 a 
a:
[[ 4  2 -2]
 [ 2 -2  2]]
b:
[[ 0 -4  3]
 [ 0 -2 -4]]
c: wrong dimensions
Sizes on matrix dont match on add
-1
d:
[[3 2]
 [2 3]]
e:
[[ 9 12]
 [12  9]]
f:
[[-4 -4]
 [-4 -4]]
g:
Sizes on matrix dont match on add
-1
h:
Sizes on matrix dont match on mult
-1
i:
[[11 10]
 [10 11]]
j:
[[  8 -10  -3]
 [ 10  -8   0]]
k:
[[1 2]
 [2 1]]
l:
[[5 2]
 [7 4]]

10.2.2:
[[29 26]
 [26 42]]

10.2.3:
AB =
[[ 4  7]
 [ 8 14]]
AC =
[[ 4  7]
 [ 8 14]]
B != C
[[2 1]
 [1 3]]
[[4 3]
 [0 2]]


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [71]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [75]:
v1 = np.arange(4)
v2 = v1[-2:]
v2[-1] =123
v3 = np.array(v1)
print(v1)
print(v2)
print(v2.base)
print(v1.base)

v3[-1] =1111 # new value in v3
print(v3)
print(v3.base)
print(v1) # v1 is not changed

# v2 is a view of v1, not a copy. when changing v2 it also change v1 as v2 "points" to v1.
# v3 is a copy of v1, change of v3 will not change v1


[  0   1   2 123]
[  2 123]
[  0   1   2 123]
None
[   0    1    2 1111]
None
[  0   1   2 123]
